### ISSUE TITLE
Simply don't work

### ISSUE THREAD

**Issue by smdstudios** [dbohdan/hicolor#4]
I click on the program and there is a command line that briefly shows up before closing. Alright, I figure I then have to run it through CMD itself.

So I type _cd:\Users\Me_ into CMD (which is where I put the executable and the image, and then enter _hicolor-v0.3.1-win32.exe hicolor quantize -5 example.png_

But then it says "invalid command" and simply tells me: 
  hicolor (encode|decode|quantize) [options] src [dest]
  hicolor info file
  hicolor version
  hicolor help

I don't know what I'm being asked to do. Even _hicolor help_ produces "invalid command"

**Comment by dbohdan** [comment]
Instead of

>  hicolor-v0.3.1-win32.exe hicolor quantize -5 example.png

type

>  hicolor-v0.3.1-win32.exe quantize -5 example.png

In the usage instructions `hicolor` is the name of the program.

**Comment by smdstudios** [comment]
Sweet that worked! tysm

**Comment by dbohdan** [comment]
You're welcome!
